### ISSUE TITLE
Add vocabulary register?

### ISSUE THREAD

**Issue by GrimPixel** [Destaq/language-learning-dashboard#2]
I see you are doing a great work.

I found that [one of my ideas](https://polyglotclub.com/wiki/Language/Multiple-languages/Culture/Ideas-about-language-learning#Vocabulary_register) may come true. It is the register of all learned vocabulary with evaluation. Are you interested?

**Comment by Destaq** [comment]
While there is no database with the specific user vocabulary, figures are analyzed from file inputs e.g. from Anki or Pleco. Segmenting/parsing those files should be enough to create the 'bank' you desire, but tracking individual words rather than the _count_ of known words is outside the scope of this application.
